[package]
name = "calculator"
version = "0.1.0"
authors = ["0zAND1z <11145839+0zAND1z@users.noreply.github.com>"]
edition = "2018"

[dependencies]
meval ="*"
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
rpassword = "3.0.2"
